import {
  HeartPulse, Factory, Banknote, ShoppingCart, GraduationCap, Landmark,
  Brain, Eye, Activity, Stethoscope, Cpu, Gauge, Wrench, ShieldCheck,
  TrendingUp, Database, Bot, Camera, Truck, Zap, Droplets, Plane,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type ProjectDetail = {
  slug: string;
  title: string;
  cat: string;
  summary: string;
  problem: string;
  solution: string;
  results: string[];
  features: string[];
  tech: string[];
  icon: LucideIcon;
  color: string;
  screens: { title: string; subtitle: string; variant: "dashboard" | "card" | "phone" }[];
  price?: string;
};

export const PROJECTS: ProjectDetail[] = [
  {
    slug: "breast-cancer-vit",
    title: "تشخیص زودهنگام سرطان پستان از ماموگرافی با Vision Transformer",
    cat: "پزشکی",
    summary: "سیستم AI با دقت ۹۶٪ برای کمک به رادیولوژیست‌ها در تشخیص توده‌های مشکوک از تصاویر ماموگرافی.",
    problem: "تأخیر در تشخیص سرطان پستان و خطای انسانی در تفسیر ماموگرافی، نرخ مرگ‌ومیر را افزایش می‌دهد.",
    solution: "مدل Vision Transformer Fine-tune شده روی دیتاست CBIS-DDSM و INbreast با تکنیک Grad-CAM برای تفسیرپذیری ناحیه‌های مشکوک.",
    results: ["دقت ۹۶.۳٪ روی تست‌ست", "حساسیت ۹۴٪", "کاهش ۴۰٪ زمان تشخیص رادیولوژیست", "ROC-AUC = 0.97"],
    features: ["پشتیبانی فرمت DICOM", "تفسیرپذیری با Grad-CAM", "API REST + Web UI", "گزارش PDF خودکار"],
    tech: ["PyTorch", "ViT", "DICOM", "Grad-CAM", "FastAPI", "React", "Python", "Docker", "NumPy", "Git"],
    icon: HeartPulse, color: "from-pink-500 to-rose-500",
    screens: [
      { title: "Dashboard تشخیص", subtitle: "نمای اصلی پزشک", variant: "dashboard" },
      { title: "Heatmap توده", subtitle: "Grad-CAM روی ضایعه", variant: "card" },
      { title: "گزارش بیمار", subtitle: "خروجی PDF نهایی", variant: "card" },
    ],
  },
  {
    slug: "brain-tumor-segmentation",
    title: "سگمنتیشن تومور مغزی روی MRI با nnU-Net",
    cat: "پزشکی",
    summary: "مدل State-of-the-Art برای جداسازی دقیق تومورهای مغزی از تصاویر MRI سه‌بعدی.",
    problem: "تعیین مرز دقیق تومور مغزی برای جراحی و رادیوتراپی نیاز به ساعت‌ها کار دستی توسط متخصص دارد.",
    solution: "پیاده‌سازی nnU-Net 3D روی دیتاست BraTS 2024 با Multi-Modal MRI (T1، T1c، T2، FLAIR).",
    results: ["Dice Score = 0.91", "کاهش زمان از ۴ ساعت به ۲ دقیقه", "تأیید بالینی توسط ۳ متخصص"],
    features: ["پردازش 3D Volume", "Multi-Modal Input", "خروجی NIfTI", "اتصال به PACS"],
    tech: ["nnU-Net", "MONAI", "PyTorch", "NIfTI", "ITK-SNAP", "Python", "Docker", "NumPy", "Git"],
    icon: Brain, color: "from-purple-500 to-indigo-500",
    screens: [
      { title: "MRI Viewer 3D", subtitle: "مرور Axial/Sagittal/Coronal", variant: "dashboard" },
      { title: "Tumor Mask", subtitle: "سگمنتیشن خودکار", variant: "card" },
      { title: "گزارش حجم", subtitle: "Volumetric Analysis", variant: "card" },
    ],
  },
  {
    slug: "diabetic-retinopathy",
    title: "تشخیص رتینوپاتی دیابتی از تصاویر فوندوس",
    cat: "پزشکی",
    summary: "غربالگری خودکار رتینوپاتی دیابتی در ۵ سطح، روی موبایل و وب.",
    problem: "رتینوپاتی دیابتی اصلی‌ترین علت نابینایی بزرگسالان است و غربالگری به موقع نیاز به چشم‌پزشک متخصص دارد.",
    solution: "EfficientNet-B5 با Transfer Learning روی APTOS-2019 و EyePACS، با کالیبراسیون احتمالی.",
    results: ["دقت ۹۲٪", "Quadratic Kappa = 0.89", "Inference روی موبایل < ۱ ثانیه"],
    features: ["استقرار روی موبایل با TFLite", "Quality Check خودکار تصویر", "گزارش گرافیکی", "اتصال به HIS"],
    tech: ["EfficientNet", "TensorFlow", "TFLite", "Flutter", "Python", "Docker", "NumPy", "Git"],
    icon: Eye, color: "from-amber-500 to-orange-500",
    screens: [
      { title: "اپ موبایل پزشک", subtitle: "اسکن سریع فوندوس", variant: "phone" },
      { title: "نتیجه طبقه‌بندی", subtitle: "۵ سطح شدت", variant: "card" },
      { title: "Heatmap چشم", subtitle: "ناحیه آسیب‌دیده", variant: "card" },
    ],
  },
  {
    slug: "ecg-arrhythmia",
    title: "تشخیص آریتمی قلبی از سیگنال ECG با 1D-CNN",
    cat: "پزشکی",
    summary: "تشخیص بلادرنگ ۱۲ نوع آریتمی قلبی از سیگنال‌های ECG هولتر و دستگاه‌های پوشیدنی.",
    problem: "تحلیل دستی نوار قلب ۲۴ ساعته زمان‌بر و مستعد خطاست.",
    solution: "شبکه 1D-CNN با Attention روی دیتاست MIT-BIH و PhysioNet با Wavelet Preprocessing.",
    results: ["دقت ۹۸٪", "F1 = 0.96", "Latency = 12ms"],
    features: ["پردازش Real-time", "هشدار فوری به پزشک", "اتصال به وسایل پوشیدنی", "گزارش روزانه"],
    tech: ["1D-CNN", "PyTorch", "Wavelet", "MQTT", "Python", "Docker", "NumPy", "Git"],
    icon: Activity, color: "from-rose-500 to-red-500",
    screens: [
      { title: "ECG Monitor", subtitle: "نمایش بلادرنگ — تشخیص آریتمی", variant: "dashboard" },
      { title: "تشخیص آریتمی", subtitle: "هایلایت لحظه‌ای PVC", variant: "dashboard" },
      { title: "اپ بیمار", subtitle: "هشدار و گزارش روزانه", variant: "phone" },
      { title: "نمونه خروجی", subtitle: "گزارش پایش ECG قابل دانلود", variant: "dashboard" },
    ],
  },
  {
    slug: "icu-survival-xgboost",
    title: "پیش‌بینی بقای بیماران ICU با MIMIC-IV",
    cat: "پزشکی",
    summary: "مدل پیش‌بینی ۲۴ و ۴۸ ساعته احتمال بقای بیماران بخش مراقبت‌های ویژه.",
    problem: "تخصیص بهینه منابع ICU و اولویت‌بندی بیماران نیازمند پیش‌بینی دقیق وضعیت بالینی است.",
    solution: "XGBoost با Feature Engineering روی ۲۰۰ متغیر بالینی، با تفسیر SHAP.",
    results: ["AUC = 0.91", "Calibration عالی", "کاهش ۲۲٪ مرگ‌ومیر در آزمون پایلوت"],
    features: ["داشبورد Real-time", "تفسیر SHAP", "اتصال به HIS بیمارستان", "هشدار خودکار"],
    tech: ["XGBoost", "SHAP", "Python", "PostgreSQL", "Grafana", "Docker", "NumPy", "Git"],
    icon: Stethoscope, color: "from-cyan-500 to-blue-500",
    screens: [
      { title: "ICU Dashboard", subtitle: "وضعیت همه بیماران", variant: "dashboard" },
      { title: "تفسیر SHAP", subtitle: "علل ریسک هر بیمار", variant: "card" },
      { title: "گزارش روزانه", subtitle: "خلاصه مدیریتی", variant: "card" },
    ],
  },
  {
    slug: "steel-defect-yolov8",
    title: "تشخیص لحظه‌ای نقص خط تولید فولاد با YOLOv8",
    cat: "صنعتی",
    summary: "سیستم بینایی ماشین برای کنترل کیفیت بلادرنگ خط تولید ورق فولاد.",
    problem: "نقص‌های سطحی فولاد (ترک، خراش، حفره) باعث ضایعات سنگین و خواب خط می‌شود.",
    solution: "YOLOv8-Large روی Jetson AGX با ۴ دوربین صنعتی، خروجی به PLC برای جداسازی خودکار.",
    results: ["دقت ۹۷٪", "سرعت ۶۰ FPS", "کاهش ۳۵٪ ضایعات", "ROI طی ۴ ماه"],
    features: ["پردازش Edge", "اتصال PLC", "داشبورد مدیریتی", "آرشیو تصاویر"],
    tech: ["YOLOv8", "TensorRT", "Jetson AGX", "OpenCV", "Modbus", "Python", "Docker", "NumPy", "Git"],
    icon: Factory, color: "from-orange-500 to-red-500",
    screens: [
      { title: "Live Camera Feed", subtitle: "۴ دوربین خط تولید", variant: "dashboard" },
      { title: "Detection Overlay", subtitle: "نقص هایلایت شده", variant: "card" },
      { title: "KPI مدیریتی", subtitle: "نرخ نقص روزانه", variant: "card" },
    ],
  },
  {
    slug: "turbine-predictive-maintenance",
    title: "نگهداری پیش‌بینانه توربین‌های گازی با LSTM",
    cat: "صنعتی",
    summary: "پیش‌بینی خرابی توربین‌های گازی ۷ تا ۱۴ روز قبل از وقوع.",
    problem: "خواب اضطراری توربین گازی روزانه میلیون‌ها دلار ضرر می‌زند.",
    solution: "LSTM چندمتغیره روی داده‌های ارتعاش، دما و فشار با Anomaly Detection.",
    results: ["دقت پیش‌بینی ۸۹٪", "کاهش ۶۰٪ توقفات ناخواسته", "صرفه‌جویی $۲M سالانه"],
    features: ["مانیتورینگ ۲۴/۷", "هشدار SMS/Email", "گزارش RUL", "ادغام SCADA"],
    tech: ["LSTM", "PyTorch", "Kafka", "InfluxDB", "Grafana", "Python", "Docker", "NumPy", "Git"],
    icon: Gauge, color: "from-amber-500 to-yellow-500",
    screens: [
      { title: "Health Score", subtitle: "وضعیت هر توربین", variant: "dashboard" },
      { title: "Anomaly Detection", subtitle: "ناهنجاری ارتعاش", variant: "card" },
      { title: "RUL Forecast", subtitle: "زمان باقی‌مانده عمر", variant: "card" },
    ],
  },
  {
    slug: "safety-helmet-detection",
    title: "ایمنی هوشمند کارخانه: تشخیص نبود تجهیزات ایمنی",
    cat: "صنعتی",
    summary: "مانیتورینگ خودکار استفاده پرسنل از کلاه، جلیقه و عینک ایمنی در کارخانه.",
    problem: "حوادث ناشی از عدم رعایت ایمنی، هزینه انسانی و قانونی سنگینی دارد.",
    solution: "YOLO-NAS روی دوربین‌های موجود، با اخطار صوتی و ثبت در سیستم HSE.",
    results: ["دقت ۹۵٪", "کاهش ۸۰٪ تخلفات ایمنی", "بازگشت سرمایه طی ۳ ماه"],
    features: ["پردازش RTSP", "اخطار صوتی لحظه‌ای", "گزارش HSE", "تشخیص چهره پرسنل"],
    tech: ["YOLO-NAS", "RTSP", "Jetson Nano", "Node-RED", "Python", "Docker", "NumPy", "Git"],
    icon: ShieldCheck, color: "from-emerald-500 to-teal-500",
    screens: [
      { title: "Live Monitoring", subtitle: "همه دوربین‌ها", variant: "dashboard" },
      { title: "تخلف ثبت‌شده", subtitle: "اسنپ‌شات + زمان", variant: "card" },
      { title: "گزارش HSE", subtitle: "آمار ماهانه", variant: "card" },
    ],
  },
  {
    slug: "weld-defect-detection",
    title: "تشخیص جوش‌های معیوب لوله‌سازی با Mask R-CNN",
    cat: "صنعتی",
    summary: "تشخیص خودکار عیوب جوش از تصاویر رادیوگرافی صنعتی.",
    problem: "بازرسی تصاویر X-Ray جوش زمان‌بر و وابسته به تجربه بازرس است.",
    solution: "Mask R-CNN روی دیتاست GDXray با ۵ نوع نقص (Crack، Porosity، Slag، LOF، LOP).",
    results: ["دقت ۹۳٪", "کاهش ۷۰٪ زمان بازرسی", "تأیید استاندارد API 1104"],
    features: ["پردازش تصاویر DICONDE", "گزارش استاندارد", "آرشیو ابری", "Audit Trail"],
    tech: ["Mask R-CNN", "Detectron2", "X-Ray Imaging", "Python", "Docker", "NumPy", "Git"],
    icon: Wrench, color: "from-slate-500 to-zinc-600",
    screens: [
      { title: "X-Ray Viewer", subtitle: "تصویر رادیوگرافی", variant: "dashboard" },
      { title: "نقاشی نقص‌ها", subtitle: "Mask خودکار", variant: "card" },
      { title: "Report Builder", subtitle: "گزارش API 1104", variant: "card" },
    ],
  },
  {
    slug: "bank-fraud-realtime",
    title: "تشخیص تقلب تراکنش‌های بانکی Real-time",
    cat: "مالی",
    summary: "سیستم AI برای تشخیص آنی تراکنش‌های مشکوک کارت‌خوان و درگاه پرداخت.",
    problem: "تقلب کارت بانکی سالانه میلیاردها تومان ضرر به بانک‌ها وارد می‌کند.",
    solution: "XGBoost + Isolation Forest روی Kafka Stream با Latency کمتر از ۵۰ms.",
    results: ["Precision = 0.94", "Recall = 0.88", "False Positive < 0.1%", "صرفه‌جویی $۵M"],
    features: ["پردازش Streaming", "هشدار آنی", "Whitelist هوشمند", "داشبورد ضدتقلب"],
    tech: ["XGBoost", "Kafka", "Flink", "Redis", "Spring Boot", "Python", "Docker", "NumPy", "Git"],
    icon: Banknote, color: "from-cyan-500 to-blue-500",
    screens: [
      { title: "Fraud Console", subtitle: "تراکنش‌های مشکوک", variant: "dashboard" },
      { title: "Transaction Detail", subtitle: "تحلیل تک‌تراکنش", variant: "card" },
      { title: "آمار روزانه", subtitle: "KPI مدیریت ریسک", variant: "card" },
    ],
  },
  {
    slug: "recommendation-engine",
    title: "موتور توصیه‌گر اختصاصی فروشگاه آنلاین",
    cat: "تجاری",
    summary: "افزایش ۳۸٪ نرخ تبدیل با موتور توصیه‌گر شخصی‌سازی شده مبتنی بر Deep Learning.",
    problem: "نرخ تبدیل پایین و سبد خرید کوچک به دلیل عدم پیشنهاد محصولات مرتبط.",
    solution: "Two-Tower Neural Network + Collaborative Filtering با Real-time Personalization.",
    results: ["+۳۸٪ نرخ تبدیل", "+۲۴٪ AOV", "+۵۲٪ زمان حضور در سایت"],
    features: ["پیشنهاد لحظه‌ای", "A/B Testing داخلی", "Cold Start حل‌شده", "API استاندارد"],
    tech: ["TensorFlow", "FAISS", "Redis", "FastAPI", "ClickHouse", "Python", "Docker", "NumPy", "Git"],
    icon: ShoppingCart, color: "from-emerald-500 to-teal-500",
    screens: [
      { title: "Recommendation Panel", subtitle: "روی صفحه محصول", variant: "dashboard" },
      { title: "A/B Test Dashboard", subtitle: "مقایسه نسخه‌ها", variant: "card" },
      { title: "Analytics Tab", subtitle: "تأثیر روی فروش", variant: "card" },
    ],
  },
  {
    slug: "smart-city-tabriz",
    title: "سیستم نظارت تصویری شهر هوشمند تبریز",
    cat: "دولتی",
    summary: "تحلیل بلادرنگ ترافیک، پلاک‌خوانی و تشخیص حوادث در سطح شهر.",
    problem: "مدیریت ترافیک شهری بدون داده دقیق بلادرنگ ممکن نیست.",
    solution: "شبکه ۳۰۰ دوربین + Edge AI + پلتفرم مرکزی با YOLO + DeepSort.",
    results: ["کاهش ۱۸٪ ترافیک", "افزایش ۴۲٪ نرخ کشف تخلف", "زمان واکنش حوادث −۳۵٪"],
    features: ["پلاک‌خوانی فارسی", "تشخیص تصادف", "شمارش خودرو", "نقشه گرمایی ترافیک"],
    tech: ["YOLOv8", "DeepSort", "PaddleOCR", "TensorRT", "Kafka", "Python", "Docker", "NumPy", "Git"],
    icon: Landmark, color: "from-amber-500 to-yellow-500",
    screens: [
      { title: "City Control Room", subtitle: "نقشه + دوربین‌ها", variant: "dashboard" },
      { title: "ANPR Live", subtitle: "پلاک‌خوانی بلادرنگ", variant: "card" },
      { title: "Incident Alert", subtitle: "تشخیص خودکار تصادف", variant: "card" },
    ],
  },
  {
    slug: "persian-llm-finetune",
    title: "Fine-tune مدل LLM فارسی برای تولید محتوا",
    cat: "تجاری",
    summary: "Fine-tune مدل LLaMA 3 فارسی برای تولید مقاله، خلاصه و پاسخگویی تخصصی.",
    problem: "مدل‌های عمومی در فارسی کیفیت پایین دارند و درک حوزه تخصصی ندارند.",
    solution: "LoRA + QLoRA روی ۲M متن فارسی + RLHF برای هم‌ترازی.",
    results: ["BLEU = 42", "ROUGE-L = 0.58", "ارزیابی انسانی ۸.۷/۱۰"],
    features: ["تولید مقاله", "خلاصه‌سازی هوشمند", "پاسخگویی تخصصی", "API ابری"],
    tech: ["LLaMA 3", "LoRA", "PEFT", "TRL", "vLLM", "Python", "Docker", "NumPy", "Git"],
    icon: Bot, color: "from-violet-500 to-fuchsia-500",
    screens: [
      { title: "Playground", subtitle: "تست مدل آنلاین", variant: "dashboard" },
      { title: "Article Generator", subtitle: "تولید مقاله بلند", variant: "card" },
      { title: "API Docs", subtitle: "مستندات یکپارچه‌سازی", variant: "card" },
    ],
  },
  {
    slug: "phd-bayesian-finance",
    title: "پایان‌نامه دکتری: مدل‌سازی Bayesian سری‌های زمانی مالی",
    cat: "دانشگاهی",
    summary: "پیاده‌سازی مدل Stochastic Volatility بیزی برای پیش‌بینی نوسانات بازار سرمایه.",
    problem: "مدل‌های GARCH کلاسیک عدم قطعیت را به‌خوبی کمی‌سازی نمی‌کنند.",
    solution: "Hamiltonian Monte Carlo با PyMC و Stan روی داده‌های ۱۰ ساله شاخص کل بورس.",
    results: ["انتشار در ژورنال Q1", "بهبود ۲۳٪ نسبت به GARCH", "پذیرفته شده ICML Workshop"],
    features: ["MCMC Diagnostics", "Posterior Predictive Check", "بازنمایی عدم قطعیت", "Replication Package"],
    tech: ["PyMC", "Stan", "R", "ArviZ", "LaTeX", "Python", "Docker", "NumPy", "Git"],
    icon: TrendingUp, color: "from-indigo-500 to-blue-500",
    screens: [
      { title: "Posterior Plot", subtitle: "توزیع پسین پارامترها", variant: "dashboard" },
      { title: "Forecast Bands", subtitle: "پیش‌بینی با عدم قطعیت", variant: "card" },
      { title: "نگارش پایان‌نامه", subtitle: "فصل ۴ آماده", variant: "card" },
    ],
  },
  {
    slug: "oil-pipeline-leak-detection",
    title: "تشخیص نشت خطوط لوله نفت و گاز با Acoustic AI",
    cat: "صنعتی",
    summary: "سیستم AI مبتنی بر سنسورهای آکوستیک و فیبر نوری برای تشخیص نشت در کمتر از ۳۰ ثانیه.",
    problem: "نشت‌های کوچک خطوط لوله نفت/گاز ساعت‌ها بدون تشخیص می‌مانند و خسارت زیست‌محیطی و مالی سنگین می‌سازند.",
    solution: "تلفیق DAS (Distributed Acoustic Sensing) با 1D-CNN + Transformer روی فریم‌های زمان-فرکانس و طبقه‌بندی شدت نشت.",
    results: ["زمان تشخیص < ۳۰s", "دقت ۹۶٪", "کاهش ۷۰٪ هشدارهای کاذب", "پایلوت ۱۲۰ کیلومتر خط"],
    features: ["پردازش DAS Real-time", "نقشه GIS نشت‌ها", "هشدار SCADA/SMS", "تخمین حجم نشت"],
    tech: ["Python", "PyTorch", "Transformer", "DAS Fiber", "Kafka", "PostGIS", "Docker", "Git"],
    icon: Droplets, color: "from-blue-500 to-cyan-500",
    screens: [
      { title: "نقشه GIS خط لوله", subtitle: "موقعیت سنسورها", variant: "dashboard" },
      { title: "Spectrogram نشت", subtitle: "تحلیل آکوستیک", variant: "card" },
      { title: "هشدار اپراتور", subtitle: "اقدام پیشنهادی", variant: "card" },
    ],
  },
  {
    slug: "power-grid-load-forecast",
    title: "پیش‌بینی بار شبکه برق با Temporal Fusion Transformer",
    cat: "صنعتی",
    summary: "پیش‌بینی دقیق بار مصرفی شبکه برق در افق ۲۴ ساعته با خطای کمتر از ۲٪.",
    problem: "خطای پیش‌بینی بار باعث Curtailment تجدیدپذیرها، هزینه peaker، یا قطعی برق می‌شود.",
    solution: "TFT با Covariates هواشناسی، تقویم تعطیلات و قیمت بازار برق روی داده‌های SCADA پنج ساله.",
    results: ["MAPE = 1.8٪", "صرفه‌جویی $۳.۲M سالانه", "کاهش ۲۴٪ Reserve Margin"],
    features: ["پیش‌بینی Probabilistic", "ادغام با EMS", "What-if Scenario", "Dashboard مدیریت"],
    tech: ["Python", "PyTorch Forecasting", "TFT", "Airflow", "TimescaleDB", "NumPy", "Docker", "Git"],
    icon: Zap, color: "from-yellow-500 to-amber-500",
    screens: [
      { title: "Load Forecast 24h", subtitle: "با Confidence Interval", variant: "dashboard" },
      { title: "What-if Panel", subtitle: "سناریوهای آب‌وهوا", variant: "card" },
      { title: "Cost Saving KPI", subtitle: "گزارش مدیریتی", variant: "card" },
    ],
  },
  {
    slug: "logistics-route-optimization",
    title: "بهینه‌سازی مسیر ناوگان لجستیک با Reinforcement Learning",
    cat: "صنعتی",
    summary: "کاهش ۲۸٪ هزینه سوخت و زمان تحویل با مسیریابی پویا مبتنی بر RL.",
    problem: "مسیریابی ثابت با تغییرات ترافیک، تقاضای لحظه‌ای و پنجره زمانی مشتری سازگار نیست.",
    solution: "Deep RL (PPO) با شبیه‌سازی ترافیک شهری + داده ماهواره‌ای، Online Re-planning هر ۵ دقیقه.",
    results: ["کاهش ۲۸٪ هزینه سوخت", "تحویل به‌موقع ۹۶٪", "−۲۲٪ کیلومتر روزانه"],
    features: ["Dynamic Re-routing", "تخصیص خودرو/راننده", "ادغام TMS", "اپ راننده"],
    tech: ["Python", "Ray RLlib", "PPO", "OR-Tools", "Mapbox", "FastAPI", "Docker", "Git"],
    icon: Truck, color: "from-emerald-500 to-green-600",
    screens: [
      { title: "Fleet Map", subtitle: "موقعیت زنده ناوگان", variant: "dashboard" },
      { title: "Route Optimizer", subtitle: "مقایسه قبل/بعد", variant: "card" },
      { title: "Driver App", subtitle: "Turn-by-turn", variant: "phone" },
    ],
  },
  {
    slug: "aviation-anomaly-detection",
    title: "تشخیص ناهنجاری موتور هواپیما با Autoencoder",
    cat: "صنعتی",
    summary: "پایش بلادرنگ ۵۰۰+ پارامتر موتور هواپیما و تشخیص ناهنجاری قبل از وقوع خرابی.",
    problem: "خرابی موتور در پرواز فاجعه‌بار و توقف اضطراری هواپیما برای ایرلاین میلیون‌ها دلار هزینه دارد.",
    solution: "Variational Autoencoder + Isolation Forest روی داده‌های QAR، با Severity Scoring و طبقه‌بندی نوع خرابی.",
    results: ["تشخیص ۸۹٪ خرابی‌ها قبل از Fault", "کاهش ۴۲٪ AOG", "صرفه‌جویی $۸M ناوگان"],
    features: ["پایش QAR Real-time", "Severity Score", "ادغام MRO", "گزارش مهندسی"],
    tech: ["Python", "TensorFlow", "VAE", "Spark", "Cassandra", "Pandas", "Docker", "Git"],
    icon: Plane, color: "from-sky-500 to-indigo-500",
    screens: [
      { title: "Engine Health", subtitle: "همه ناوگان", variant: "dashboard" },
      { title: "Anomaly Detail", subtitle: "ریشه‌یابی", variant: "card" },
      { title: "MRO Workorder", subtitle: "صدور خودکار", variant: "card" },
    ],
  },
];

export const getProjectBySlug = (slug: string) => PROJECTS.find((p) => p.slug === slug);
