import {
  Brain, Bot, BarChart3, Database, LineChart, Code2, FileText,
  Smartphone, Globe, Cloud, Presentation, BookOpen, GraduationCap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type ServiceDetail = {
  slug: string;
  title: string;
  tagline: string;
  desc: string;
  icon: LucideIcon;
  color: string;
  features: string[];
  technologies: string[];
  useCases: { title: string; desc: string }[];
  process: { step: string; desc: string }[];
  deliverables: string[];
};

export const SERVICE_DETAILS: ServiceDetail[] = [
  {
    slug: "deep-learning",
    title: "یادگیری عمیق",
    tagline: "شبکه‌های عصبی پیشرفته برای حل پیچیده‌ترین مسائل",
    desc: "از طراحی معماری اختصاصی شبکه عصبی تا آموزش، Fine-tune و استقرار مدل‌های Transformer، CNN، RNN و LLM در محیط Production.",
    icon: Brain,
    color: "from-purple-500 to-indigo-500",
    features: [
      "طراحی معماری اختصاصی شبکه عصبی متناسب با داده شما",
      "آموزش روی GPU و TPU با تکنیک‌های Mixed Precision",
      "Transfer Learning و Fine-Tune مدل‌های Pretrained",
      "بهینه‌سازی، Pruning و Quantization مدل برای Edge",
      "تفسیرپذیری مدل با Grad-CAM، SHAP و LIME",
    ],
    technologies: ["PyTorch", "TensorFlow", "Keras", "JAX", "Hugging Face", "ONNX", "CUDA", "TensorRT"],
    useCases: [
      { title: "تشخیص پزشکی", desc: "تشخیص بیماری از تصاویر MRI، CT و فوندوس با دقت بالای ۹۵٪." },
      { title: "بینایی صنعتی", desc: "کنترل کیفیت Real-time خط تولید با YOLO و Vision Transformer." },
      { title: "پردازش زبان", desc: "ساخت چت‌بات‌های اختصاصی فارسی و خلاصه‌سازی هوشمند متون." },
    ],
    process: [
      { step: "تحلیل داده", desc: "بررسی کیفیت، حجم و ساختار داده ورودی" },
      { step: "طراحی معماری", desc: "انتخاب بهترین معماری متناسب با مسئله" },
      { step: "آموزش و Tuning", desc: "آموزش روی GPU و تنظیم Hyperparameter" },
      { step: "ارزیابی و استقرار", desc: "تست، بهینه‌سازی و Deploy نهایی" },
    ],
    deliverables: ["مدل آموزش‌دیده", "کد کامل قابل اجرا", "مستندات فنی", "گزارش ارزیابی", "پشتیبانی پس از تحویل"],
  },
  {
    slug: "machine-learning",
    title: "یادگیری ماشین",
    tagline: "از داده‌های خام تا تصمیم‌های هوشمند",
    desc: "پیاده‌سازی الگوریتم‌های کلاسیک و مدرن ML برای دسته‌بندی، رگرسیون، خوشه‌بندی و یادگیری تقویتی.",
    icon: Bot,
    color: "from-cyan-500 to-blue-500",
    features: [
      "پیاده‌سازی Supervised، Unsupervised و Reinforcement Learning",
      "Feature Engineering حرفه‌ای و انتخاب ویژگی",
      "Ensemble Models و Boosting (XGBoost، LightGBM، CatBoost)",
      "AutoML و Hyperparameter Tuning خودکار",
      "تفسیر مدل و گزارش‌گیری مدیریتی",
    ],
    technologies: ["scikit-learn", "XGBoost", "LightGBM", "CatBoost", "Optuna", "MLflow", "Pandas", "NumPy"],
    useCases: [
      { title: "پیش‌بینی فروش", desc: "پیش‌بینی دقیق تقاضا و موجودی انبار برای فروشگاه‌ها." },
      { title: "تشخیص تقلب", desc: "شناسایی تراکنش‌های مشکوک بانکی Real-time." },
      { title: "Customer Segmentation", desc: "بخش‌بندی هوشمند مشتریان برای کمپین‌های هدفمند." },
    ],
    process: [
      { step: "EDA", desc: "تحلیل اکتشافی داده‌ها و کشف الگوها" },
      { step: "Feature Engineering", desc: "ساخت و انتخاب ویژگی‌های مؤثر" },
      { step: "Model Selection", desc: "مقایسه و انتخاب بهترین الگوریتم" },
      { step: "Deploy و Monitor", desc: "استقرار و نظارت بر کارایی مدل" },
    ],
    deliverables: ["مدل ML", "گزارش EDA کامل", "Pipeline قابل تکرار", "API پیش‌بینی", "داشبورد تحلیلی"],
  },
  {
    slug: "statistical-analysis",
    title: "تحلیل آماری",
    tagline: "تصمیم‌گیری دقیق بر پایه شواهد علمی",
    desc: "تحلیل‌های آماری توصیفی و استنباطی، مدل‌سازی چندمتغیره، آزمون فرض و آمار بیزی برای پایان‌نامه و پژوهش.",
    icon: BarChart3,
    color: "from-amber-500 to-orange-500",
    features: [
      "آزمون فرض پارامتریک و ناپارامتریک",
      "رگرسیون خطی، لجستیک، چندجمله‌ای و هرمی (HLM)",
      "ANOVA، MANOVA، ANCOVA و طرح‌های آزمایش",
      "تحلیل عاملی، مسیر و معادلات ساختاری (SEM)",
      "آمار بیزی، MCMC و Bayesian Networks",
    ],
    technologies: ["SPSS", "R", "STATA", "AMOS", "SmartPLS", "JASP", "PyMC", "Stan"],
    useCases: [
      { title: "پایان‌نامه ارشد و دکتری", desc: "تحلیل آماری کامل با نگارش فصل ۴ و گزارش APA." },
      { title: "پژوهش پزشکی و رفتاری", desc: "متاآنالیز، Survival Analysis و آزمون‌های بالینی." },
      { title: "پژوهش بازار", desc: "تحلیل پرسشنامه، اعتبار، روایی و SEM." },
    ],
    process: [
      { step: "طراحی پژوهش", desc: "تعیین فرضیه‌ها و انتخاب آزمون مناسب" },
      { step: "آماده‌سازی داده", desc: "پاکسازی، بازکدگذاری و بررسی پیش‌فرض‌ها" },
      { step: "تحلیل", desc: "اجرای آزمون‌ها و مدل‌سازی آماری" },
      { step: "گزارش", desc: "نگارش حرفه‌ای فصل ۴ پایان‌نامه" },
    ],
    deliverables: ["فایل خروجی SPSS/R", "گزارش تحلیل کامل", "جداول استاندارد APA", "تفسیر فارسی نتایج", "آماده‌سازی برای دفاع"],
  },
  {
    slug: "data-science",
    title: "علم داده و Big Data",
    tagline: "از داده‌های پیچیده تا بینش‌های کسب‌وکاری",
    desc: "پایپ‌لاین کامل ETL، پاکسازی، تحلیل، بصری‌سازی و طراحی Data Warehouse برای سازمان‌های داده‌محور.",
    icon: Database,
    color: "from-emerald-500 to-teal-500",
    features: [
      "طراحی Pipeline داده Real-time و Batch",
      "ETL/ELT با Airflow، dbt و Spark",
      "Data Lake و Data Warehouse Architecture",
      "بصری‌سازی پیشرفته با Power BI و Tableau",
      "Big Data Processing با Hadoop و Spark",
    ],
    technologies: ["Apache Spark", "Airflow", "dbt", "Snowflake", "BigQuery", "Power BI", "Tableau", "Kafka"],
    useCases: [
      { title: "داشبورد مدیریتی", desc: "BI Real-time برای مانیتورینگ KPI سازمان." },
      { title: "Data Warehouse بانکی", desc: "طراحی DWH برای میلیاردها تراکنش." },
      { title: "تحلیل لاگ", desc: "پردازش لاگ‌های سرور و کشف رفتار کاربران." },
    ],
    process: [
      { step: "Discovery", desc: "بررسی منابع داده و نیازمندی‌ها" },
      { step: "Architecture", desc: "طراحی معماری داده مقیاس‌پذیر" },
      { step: "Implementation", desc: "پیاده‌سازی ETL و انبار داده" },
      { step: "Visualization", desc: "ساخت داشبورد و گزارش‌های تعاملی" },
    ],
    deliverables: ["معماری داده", "Pipeline‌های ETL", "Data Warehouse", "داشبورد BI", "مستندات کامل"],
  },
  {
    slug: "time-series",
    title: "پیش‌بینی سری زمانی",
    tagline: "آینده کسب‌وکار شما را امروز ببینید",
    desc: "مدل‌سازی پیش‌بینی فروش، قیمت، تقاضا و رفتار بازار با ARIMA، Prophet، LSTM و Transformer سری زمانی.",
    icon: LineChart,
    color: "from-pink-500 to-rose-500",
    features: [
      "مدل‌های آماری ARIMA، SARIMA، VAR و GARCH",
      "Deep Learning با LSTM، GRU و Temporal Fusion Transformer",
      "Anomaly Detection در سری زمانی",
      "Multi-step و Multi-variate Forecasting",
      "پیش‌بینی با عدم قطعیت (Probabilistic Forecasting)",
    ],
    technologies: ["Prophet", "statsmodels", "Darts", "GluonTS", "Kats", "PyTorch Forecasting"],
    useCases: [
      { title: "پیش‌بینی فروش", desc: "پیش‌بینی روزانه/هفتگی فروش و موجودی." },
      { title: "بازارهای مالی", desc: "مدل‌سازی قیمت سهام، طلا و رمزارز." },
      { title: "مصرف انرژی", desc: "پیش‌بینی بار شبکه برق و گاز." },
    ],
    process: [
      { step: "تحلیل سری", desc: "بررسی فصلی بودن، روند و ایستایی" },
      { step: "Modeling", desc: "آموزش مدل‌های آماری و عمیق" },
      { step: "Backtesting", desc: "ارزیابی روی داده‌های گذشته" },
      { step: "Forecast", desc: "پیش‌بینی نهایی با بازه اطمینان" },
    ],
    deliverables: ["مدل پیش‌بینی", "گزارش دقت", "نمودارهای تعاملی", "API پیش‌بینی", "داشبورد مانیتورینگ"],
  },
  {
    slug: "thesis-implementation",
    title: "پیاده‌سازی پایان‌نامه",
    tagline: "از ایده تا دفاع موفق",
    desc: "اجرای کامل پایان‌نامه کارشناسی، ارشد و دکتری همراه با کدنویسی، اجرا، تحلیل، گزارش و آماده‌سازی دفاع.",
    icon: Code2,
    color: "from-fuchsia-500 to-purple-500",
    features: [
      "پیاده‌سازی کامل الگوریتم‌های مقاله بیس",
      "بهبود و توسعه روش پیشنهادی",
      "مقایسه با State-of-the-Art",
      "نگارش فصل ۴ پایان‌نامه",
      "آماده‌سازی اسلاید و کوچینگ دفاع",
    ],
    technologies: ["Python", "MATLAB", "R", "Java", "C++", "LaTeX"],
    useCases: [
      { title: "پایان‌نامه AI/ML", desc: "پیاده‌سازی کامل با مجموعه داده استاندارد." },
      { title: "پایان‌نامه مهندسی", desc: "شبیه‌سازی و تحلیل عددی پیشرفته." },
      { title: "پایان‌نامه پزشکی", desc: "تحلیل داده بالینی و مدل‌سازی." },
    ],
    process: [
      { step: "مطالعه مقاله", desc: "بررسی دقیق مقاله بیس" },
      { step: "Implementation", desc: "کدنویسی و اجرا" },
      { step: "Comparison", desc: "مقایسه با روش‌های موجود" },
      { step: "Documentation", desc: "نگارش فصل ۴ و دفاع" },
    ],
    deliverables: ["کد کامل اجرایی", "فصل ۴ پایان‌نامه", "نتایج و نمودارها", "اسلاید دفاع", "کوچینگ دفاعیه"],
  },
  {
    slug: "scientific-writing",
    title: "مقاله‌نویسی علمی ISI/Q1",
    tagline: "از پژوهش شما تا انتشار جهانی",
    desc: "نگارش، ترجمه تخصصی، ادیت نیتیو و سابمیت مقاله در ژورنال‌های ISI، Scopus، Q1 و کنفرانس‌های معتبر دنیا.",
    icon: FileText,
    color: "from-rose-500 to-red-500",
    features: [
      "نگارش مقاله از صفر بر اساس داده شما",
      "ترجمه تخصصی فارسی به انگلیسی",
      "ادیت نیتیو توسط متخصصان زبان",
      "انتخاب ژورنال مناسب و سابمیت",
      "پاسخ به ریوایزر و بازنویسی",
    ],
    technologies: ["LaTeX", "Overleaf", "EndNote", "Grammarly", "Mendeley"],
    useCases: [
      { title: "مقاله Q1 و Q2", desc: "نگارش حرفه‌ای برای ژورنال‌های IEEE، Elsevier، Springer." },
      { title: "Review Paper", desc: "مرور سیستماتیک و متاآنالیز." },
      { title: "Conference Paper", desc: "مقاله برای کنفرانس‌های NeurIPS، CVPR، ICML." },
    ],
    process: [
      { step: "Outline", desc: "طراحی ساختار مقاله" },
      { step: "Writing", desc: "نگارش بخش به بخش" },
      { step: "Editing", desc: "ادیت نیتیو و بازخوانی" },
      { step: "Submission", desc: "سابمیت و پیگیری" },
    ],
    deliverables: ["فایل مقاله نهایی", "Cover Letter", "Response to Reviewers", "گواهی ادیت نیتیو"],
  },
  {
    slug: "ai-apps",
    title: "طراحی و ساخت اپلیکیشن AI",
    tagline: "ایده هوشمند خود را به محصول تبدیل کنید",
    desc: "طراحی و توسعه اپلیکیشن موبایل اندروید، iOS و کراس‌پلتفرم با هسته هوش مصنوعی برای استارتاپ‌ها و کسب‌وکارها.",
    icon: Smartphone,
    color: "from-sky-500 to-cyan-500",
    features: [
      "اپلیکیشن Native Android و iOS",
      "کراس‌پلتفرم با Flutter و React Native",
      "ادغام مدل‌های AI روی دیوایس (TensorFlow Lite، Core ML)",
      "ادغام API های LLM و Generative AI",
      "طراحی UI/UX مدرن و حرفه‌ای",
    ],
    technologies: ["Flutter", "React Native", "Swift", "Kotlin", "TensorFlow Lite", "Core ML", "Firebase"],
    useCases: [
      { title: "اپ پزشکی هوشمند", desc: "تشخیص بیماری از تصویر روی موبایل." },
      { title: "دستیار صوتی فارسی", desc: "STT/TTS فارسی با LLM." },
      { title: "اپ تجاری AI", desc: "توصیه‌گر محصول و چت‌بات فروش." },
    ],
    process: [
      { step: "Discovery", desc: "تحلیل نیاز و User Story" },
      { step: "UI/UX Design", desc: "طراحی پروتوتایپ تعاملی" },
      { step: "Development", desc: "توسعه فرانت و بک‌اند" },
      { step: "Launch", desc: "انتشار در استورها" },
    ],
    deliverables: ["اپ کامل اندروید/iOS", "بک‌اند و API", "Source Code", "انتشار در Store", "پشتیبانی ۶ ماهه"],
  },
  {
    slug: "smart-website",
    title: "طراحی وبسایت هوشمند",
    tagline: "وبسایتی که فکر می‌کند",
    desc: "طراحی وبسایت مدرن، Responsive و سریع همراه با چت‌بات هوشمند، سیستم توصیه‌گر و موتور جستجوی AI.",
    icon: Globe,
    color: "from-indigo-500 to-blue-500",
    features: [
      "طراحی Modern و Premium UI/UX",
      "Performance و SEO حرفه‌ای",
      "ادغام چت‌بات LLM فارسی",
      "سیستم توصیه‌گر محصول و محتوا",
      "داشبورد ادمین و آنالیتیکس",
    ],
    technologies: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Node.js", "PostgreSQL"],
    useCases: [
      { title: "فروشگاه آنلاین AI", desc: "توصیه‌گر هوشمند و جستجوی سمنتیک." },
      { title: "وبسایت سازمانی", desc: "پنل مدیریت و چت پشتیبانی AI." },
      { title: "پلتفرم محتوایی", desc: "خلاصه‌سازی و دسته‌بندی خودکار محتوا." },
    ],
    process: [
      { step: "طراحی", desc: "UI/UX و پروتوتایپ Figma" },
      { step: "Development", desc: "توسعه فرانت و بک" },
      { step: "AI Integration", desc: "ادغام قابلیت‌های هوشمند" },
      { step: "Launch", desc: "Deploy روی CDN جهانی" },
    ],
    deliverables: ["وبسایت کامل Responsive", "پنل مدیریت", "چت‌بات", "SEO Setup", "هاست و دامنه"],
  },
  {
    slug: "mlops",
    title: "MLOps و استقرار ابری",
    tagline: "از مدل آزمایشی تا Production مقیاس‌پذیر",
    desc: "Dockerize، Kubernetes، CI/CD، Monitoring و استقرار مدل‌های ML روی AWS، GCP و Azure با کیفیت Enterprise.",
    icon: Cloud,
    color: "from-teal-500 to-emerald-500",
    features: [
      "Containerization با Docker و Kubernetes",
      "CI/CD Pipeline برای مدل‌های ML",
      "Model Monitoring و Drift Detection",
      "A/B Testing و Canary Deployment",
      "Auto-scaling و Load Balancing",
    ],
    technologies: ["Docker", "Kubernetes", "MLflow", "Kubeflow", "AWS SageMaker", "GCP Vertex AI", "Azure ML"],
    useCases: [
      { title: "API پیش‌بینی مقیاس‌پذیر", desc: "Serving میلیون درخواست در روز." },
      { title: "Batch Inference", desc: "پردازش حجم بالا روی Spark Cluster." },
      { title: "Edge Deployment", desc: "استقرار مدل روی Jetson و موبایل." },
    ],
    process: [
      { step: "Audit", desc: "بررسی مدل و زیرساخت موجود" },
      { step: "Containerize", desc: "Docker و K8s" },
      { step: "CI/CD", desc: "اتوماسیون آموزش و دیپلوی" },
      { step: "Monitor", desc: "نظارت بر کارایی مدل" },
    ],
    deliverables: ["Container Image", "K8s Manifests", "CI/CD Pipeline", "Dashboard مانیتورینگ", "مستندات DevOps"],
  },
  {
    slug: "training",
    title: "تدریس و کارگاه تخصصی",
    tagline: "دانش روزآمد، با تجربه واقعی",
    desc: "دوره‌های خصوصی، گروهی و سازمانی Python، یادگیری ماشین، عمیق، LLM و علم داده با پروژه عملی واقعی.",
    icon: Presentation,
    color: "from-amber-500 to-yellow-500",
    features: [
      "دوره خصوصی One-on-One",
      "کارگاه سازمانی برای تیم‌های فنی",
      "محتوا و پروژه اختصاصی متناسب با سطح",
      "ضبط جلسات و پشتیبانی نامحدود",
      "گواهی پایان دوره معتبر",
    ],
    technologies: ["Python", "PyTorch", "TensorFlow", "LangChain", "Jupyter"],
    useCases: [
      { title: "آموزش سازمانی", desc: "Upskilling تیم Data و IT شرکت‌ها." },
      { title: "دوره دانشجویی", desc: "آماده‌سازی برای پایان‌نامه و کار." },
      { title: "کارگاه LLM", desc: "Fine-tune و RAG عملی." },
    ],
    process: [
      { step: "نیازسنجی", desc: "بررسی سطح و هدف یادگیرنده" },
      { step: "طراحی سرفصل", desc: "محتوای اختصاصی و پروژه‌محور" },
      { step: "تدریس", desc: "جلسات تعاملی آنلاین/حضوری" },
      { step: "پروژه پایانی", desc: "اجرای پروژه واقعی" },
    ],
    deliverables: ["محتوای آموزشی", "ضبط جلسات", "کدها و نوت‌بوک‌ها", "پروژه پایانی", "گواهی"],
  },
  {
    slug: "proposal-defense",
    title: "مشاوره پروپوزال و دفاع",
    tagline: "موضوع نو، دفاع قوی",
    desc: "انتخاب موضوع نوآور و به‌روز، نگارش پروپوزال حرفه‌ای، طراحی اسلاید دفاع و کوچینگ تخصصی جلسه دفاعیه.",
    icon: BookOpen,
    color: "from-violet-500 to-fuchsia-500",
    features: [
      "پیشنهاد ۵ موضوع نوآور و قابل دفاع",
      "مرور ادبیات و State-of-the-Art",
      "نگارش کامل پروپوزال ارشد و دکتری",
      "طراحی اسلاید حرفه‌ای دفاع",
      "کوچینگ و تمرین جلسه دفاعیه",
    ],
    technologies: ["LaTeX", "PowerPoint", "Beamer", "Mendeley"],
    useCases: [
      { title: "پروپوزال دکتری", desc: "موضوع نوآور با گپ پژوهشی روشن." },
      { title: "پروپوزال ارشد", desc: "موضوع به‌روز و قابل اجرا در زمان محدود." },
      { title: "آماده‌سازی دفاع", desc: "تمرین Q&A و کوچینگ کامل." },
    ],
    process: [
      { step: "ایده‌پردازی", desc: "بررسی علاقه و رشته" },
      { step: "Literature Review", desc: "مرور مقالات روز" },
      { step: "نگارش پروپوزال", desc: "تدوین حرفه‌ای" },
      { step: "دفاع", desc: "اسلاید و کوچینگ" },
    ],
    deliverables: ["پروپوزال کامل", "مرور ادبیات", "اسلاید دفاع", "تمرین جلسه دفاع"],
  },
  {
    slug: "kids-courses",
    title: "دوره‌های آموزشی کودکان و نوجوانان",
    tagline: "آموزش هوش مصنوعی، برنامه‌نویسی و تفکر داده‌محور برای تمامی سنین",
    desc: "دوره‌های پلکانی برای کودکان، نوجوانان، دانش‌آموزان و دانشجویان — از آشنایی بازی‌محور با هوش مصنوعی تا پایتون، رباتیک، علم داده و آمادگی المپیاد و کنکور رشته‌های فنی.",
    icon: GraduationCap,
    color: "from-pink-500 to-amber-500",
    features: [
      "گروه سنی ۶ تا ۹ سال: آشنایی بازی‌محور با هوش مصنوعی و تفکر منطقی",
      "گروه سنی ۱۰ تا ۱۴ سال: اسکرَچ، پایتون مقدماتی و رباتیک سرگرم‌کننده",
      "گروه سنی ۱۵ تا ۱۸ سال: پایتون پیشرفته، یادگیری ماشین و آمادگی المپیاد",
      "دانشجویان: علم داده، Deep Learning و پروژه‌محور صنعتی",
      "کلاس‌های آنلاین و حضوری در تبریز با گواهی پایان دوره",
      "آزمون استعدادسنجی رایگان قبل از ثبت‌نام",
    ],
    technologies: ["Scratch", "Python", "MicroPython", "Arduino", "TensorFlow Lite", "Teachable Machine", "Colab"],
    useCases: [
      { title: "کودک ۶–۹ سال", desc: "بازی‌های هوشمند، آشنایی با کامپیوتر و خلاقیت دیجیتال." },
      { title: "نوجوان ۱۰–۱۴ سال", desc: "ساخت بازی و ربات با Scratch، Arduino و پایتون." },
      { title: "دبیرستانی ۱۵–۱۸ سال", desc: "مدل‌سازی داده، شبکه‌های عصبی و آمادگی المپیاد." },
      { title: "دانشجو و بزرگسال", desc: "علم داده، Deep Learning و پورتفولیوی کاری." },
    ],
    process: [
      { step: "استعدادسنجی", desc: "آزمون کوتاه برای انتخاب مسیر مناسب" },
      { step: "ثبت‌نام و گروه‌بندی", desc: "گروه‌های هم‌سن و هم‌سطح" },
      { step: "آموزش پروژه‌محور", desc: "هر جلسه یک خروجی قابل ارائه" },
      { step: "گواهی و مشاوره ادامه مسیر", desc: "گواهی پایان دوره و راهنمایی شغلی" },
    ],
    deliverables: ["گواهی پایان دوره", "پروژه عملی نهایی", "ویدیوی جلسات", "پشتیبانی در گروه خصوصی", "تخفیف دوره بعدی"],
  },
];

export const getServiceBySlug = (slug: string) =>
  SERVICE_DETAILS.find((s) => s.slug === slug);
